version: '3.1'

services:
  redmine:
    container_name: redmine
    image: redmine
    restart: always
    ports:
      - 3000:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: ${REDMINE_DB_PASSWORD}
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_ENCODING: utf8
    volumes:
      - ${REDMINE_DATA_DIR_PATH}:/usr/src/redmine/files
      - ${REDMINE_PLUGINS_DIR_PATH}:/usr/src/redmine/plugins
      - ${REDMINE_THEMES_DIR_PATH}:/usr/src/redmine/public/themes

  db:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: redmine
    volumes:
      - ${MARIADB_STORAGE_DIR_PATH}:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci