version: '3.1'

services:
  redmine:
    container_name: redmine
    image: redmine
    restart: always
    ports:
      - 3000:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_USERNAME: ${MYSQL_REDMINE_USER}
      REDMINE_DB_PASSWORD: ${MYSQL_REDMINE_PASSWORD}
      REDMINE_DB_DATABASE: ${MYSQL_DATABASE}
      # Default MySQL Port is 3306
      # REDMINE_DB_PORT: 3306
      REDMINE_DB_ENCODING: utf8
    volumes:
      - ${REDMINE_FILES_DIR_PATH}:/usr/src/redmine/files
      - ${REDMINE_PLUGINS_DIR_PATH}:/usr/src/redmine/plugins
      - ${REDMINE_THEMES_DIR_PATH}:/usr/src/redmine/public/themes

  db:
    container_name: mariadb
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_REDMINE_USER}
      MYSQL_PASSWORD: ${MYSQL_REDMINE_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ${MARIADB_STORAGE_DIR_PATH}:/var/lib/mysql
      - ${MARIADB_CONFD_DIR_PATH}:/etc/mysql/conf.d:ro
      - ${MARIADB_LOG_DIR_PATH}:/var/log/maria
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
